import csv
import sqlite3
import re

def csv_to_db(csv_filepath,db_filepath):
    data=[]
    with open(csv_filepath) as file:
        reader=csv.reader(file)
        for index,line in enumerate(reader):
            if (index != 0): # to skip the first row
                data.append(tuple(line))
    #print(data)

    connection = sqlite3.connect(db_filepath)
    cursor = connection.cursor()


    # Insert new rows
    rows=data
    i=1
    for row in rows:
        cursor.execute(f"INSERT INTO TimeTable_Generator_coursedata VALUES({i},?,?,?,?,?,?)", row)
        i=i+1
        # populating autogenerated id column by django using i

    connection.commit()
    connection.close()


if __name__ == "__main__":
    csv_filepath = "course_list/sem4.csv"
    db_filepath = "db.sqlite3"
    csv_to_db(csv_filepath, db_filepath)
