# Generated by Django 4.2.4 on 2023-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_Generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='course_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
