# Generated by Django 4.2.4 on 2023-08-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_Generator', '0002_remove_coursedata_id_alter_coursedata_course_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseData',
        ),
    ]
