# Generated by Django 4.2.4 on 2023-12-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable_Generator', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
    ]
